# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0002_extramortgagepayment_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loan',
            name='name',
            field=models.CharField(default='Name', max_length=30),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='name',
            field=models.CharField(default='Name', max_length=30),
        ),
    ]
