# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0004_auto_20170322_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='extramortgagepayment',
            name='mortgage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='debt.Mortgage'),
            preserve_default=False,
        ),
    ]
